# Site settings
title: Luz Angélica Caudillo-Mata, PhD
author: Luz Angélica Caudillo-Mata
email: lcaudill@eoas.ubc.ca
description: > # this means to ignore newlines until "baseurl:"
  Computational Mathematician | Industrial Postdoctoral Fellow in AI | Bridge Builder

# photo
logo: /assets/images/luz.jpg

# social links
twitter_username: lacaudillomata
github_username:  lacmajedrez

plugins:
   - jekyll-include-cache

show_excerpts: true # set to false to remove excerpts on the homepage

#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.14.1"

