# Site settings
title: Luz Angélica Caudillo-Mata, PhD
author: Luz Angélica Caudillo-Mata
email: lcaudill@eoas.ubc.ca
description: > # this means to ignore newlines until "baseurl:"
  Professional website of Luz Angélica Caudillo-Mata

# social links
twitter_username: lacaudillomata
github_username:  lacmajedrez

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal

